import { Nunito } from "next/font/google";
import "./globals.css";
import ReduxProviders from "@/providers/ReduxProviders";
import Header from "@/components/Header";
import Top from "@/components/Top";
import  { Toaster } from 'react-hot-toast';


const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "AYATRIO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Toaster/>
        <ReduxProviders>
          <Top/>
          <Header/>
          {children}
        </ReduxProviders>
      </body>
    </html>
  );
}
